---
deployment:
  tasks:
    - /bin/echo "Starting Node.js deployment"
    - export APP_DIR=/home/bigba1331/github    # Ganti ini dengan path yang sesuai
    - /bin/cp -r * $APP_DIR
    - cd $APP_DIR
    - /bin/npm install
    - /bin/pm2 restart all || /bin/pm2 start index.js --name "node-app"
